### ISSUE TITLE
Visuals Studio for Mac and golang

### ISSUE THREAD

**Issue by gedw99** [tunnelvisionlabs/LangSvcV2#88]
I am a golang programmer using c# for GUI.

Does this provide any ability to work with golang in the Visual Studio for MAC ?

**Comment by sharwell** [comment]
No, the extensibility model for Visual Studio for Mac is different from the one used by Visual Studio. There are no plans at this time to port the project.

**Comment by gedw99** [comment]
There is btw a language services for golang already.
It's maintained by sourcetree and using in production extensively.
This is why I brought it up you see.

I use golang with c# allot.
C# for GUI stuff and golang for all services on the clients and in the cloud.

The intent I am going on about is the opportunity for providing both for c# and golang.

What I am confused about is of this project adheres to the Microsoft language services.?
You see I want to build IDE that provide the language services for both because I use both as do my users 

Can you try to answer my question ?
Would really be great

**Comment by sharwell** [comment]
> What I am confused about is of this project adheres to the Microsoft language services.?

This project uses some language features provided by Visual Studio's SDK, but most of it is customized or written from scratch. My goal was to write a language service using the MEF-based approach first seen in Visual Studio 2010 rather than the older APIs used for language services in Visual Studio 2005 and 2008.

The support for Go mostly pre-dates ANTLR 4 and GoWorks, and features like the [network interpreter](https://github.com/tunnelvisionlabs/LangSvcV2/tree/master/Tvl.VisualStudio.Antlr/Parsing/Experimental/Interpreter) were early motivating examples for creating the latter. In a magical world where I could spend a bunch of time rewriting everything, I would take lessons from this project, GoWorks, the [Java debugger](https://github.com/tunnelvisionlabs/JavaForVS), and external projects including [Microsoft/MIEngine](https://github.com/Microsoft/MIEngine) and [dotnet/roslyn](https://github.com/dotnet/roslyn) to build something even better.
